/**
 * JSON Placeholder OpenAPI
 * Example spec of the well known JSON Placeholder website
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Post { 
    /**
     * record id
     */
    id: number;
    /**
     * unique user identifier
     */
    userId: string;
    /**
     * title of this Post
     */
    title: string;
    /**
     * description of this post
     */
    body: string;
}

